# Generated by Django 4.1.4 on 2022-12-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField(default={'en': '', 'ru': '', 'uz': ''}, max_length=128)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('logo', models.ImageField(upload_to='sayt')),
                ('social', models.JSONField(default={'facebook': '', 'instagram': '', 'telegram': '', 'web': ''})),
            ],
        ),
    ]
