# Generated by Django 4.1.4 on 2022-12-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmain', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(default={'chi': '', 'de': '', 'en': '', 'ja': '', 'ru': '', 'uz': '', 'zn': ''})),
                ('desc', models.JSONField(default={'chi': '', 'de': '', 'en': '', 'ja': '', 'ru': '', 'uz': '', 'zn': ''})),
                ('img', models.ImageField(upload_to='about_course')),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
