# Generated by Django 4.1.4 on 2022-12-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmain', '0006_aboutcourse_delete_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcourse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutcourse',
            name='updated_at',
        ),
    ]
