# Generated by Django 4.1.4 on 2022-12-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmain', '0007_remove_aboutcourse_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default={'chi': '', 'de': '', 'en': '', 'ja': '', 'ru': '', 'uz': '', 'zn': ''})),
                ('desc', models.JSONField(default={'chi': '', 'de': '', 'en': '', 'ja': '', 'ru': '', 'uz': '', 'zn': ''})),
                ('img', models.ImageField(upload_to='about_course')),
            ],
            options={
                'verbose_name': 'Course',
            },
        ),
        migrations.CreateModel(
            name='OnlineWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='online_work')),
                ('desc', models.JSONField(default={'chi': '', 'de': '', 'en': '', 'ja': '', 'ru': '', 'uz': '', 'zn': ''})),
            ],
        ),
    ]
